/* Auto-generated by gen_fighter_sprite_data.py - DO NOT EDIT. */
#ifndef _SFC3_FIGHTER_SPRITE_DATA_H_
#define _SFC3_FIGHTER_SPRITE_DATA_H_
#include <Uefi.h>
#include "fighter.h"
#define SFC3_FSD_MAX_FRAMES 100
#define SFC3_FSD_MAX_LOOP   16
#define SFC3_FSD_FSTATE     8
typedef struct { UINT8 count; UINT8 flags; UINT8 ent[SFC3_FSD_MAX_LOOP][2]; } SFC3_FSD_LOOP; /* flags bit0=loop; ent[i][0]=frame_id,[i][1]=hold */
extern CONST UINT8  gFsdNFrames[FIGHTER_ID_COUNT];
extern CONST UINT8  gFsdChrOff[FIGHTER_ID_COUNT][SFC3_FSD_MAX_FRAMES];
extern CONST UINT32 gFsdFrameBase[FIGHTER_ID_COUNT];
extern CONST UINT16 gFsdFrameOff[FIGHTER_ID_COUNT][SFC3_FSD_MAX_FRAMES];
extern CONST UINT8  gFsdFrameData[55394];
extern CONST SFC3_FSD_LOOP gFsdAnim[FIGHTER_ID_COUNT][SFC3_FSD_FSTATE];
extern CONST UINT8  gFsdAnchorX[FIGHTER_ID_COUNT];
extern CONST UINT8  gFsdAnchorY[FIGHTER_ID_COUNT];
#define SFC3_VS_MAX_SPR 24
extern CONST UINT8 gVsCntP1[FIGHTER_ID_COUNT];
extern CONST UINT8 gVsChrOffP1[FIGHTER_ID_COUNT];
extern CONST UINT8 gVsRecP1[FIGHTER_ID_COUNT][SFC3_VS_MAX_SPR][3];
extern CONST UINT8 gVsCntAlt[FIGHTER_ID_COUNT];
extern CONST UINT8 gVsChrOffAlt[FIGHTER_ID_COUNT];
extern CONST UINT8 gVsRecAlt[FIGHTER_ID_COUNT][SFC3_VS_MAX_SPR][3];
#endif
